sudo: false
language: python
python:
  - 2.7
  - 3.4

install:
  #- python setup.py -q install
  - pip install -r dev-requirements.txt

script:
  - coverage run --source datacli -m py.test

after_success:
  - codecov
