version: '2'

services:

  mongo:
    build: ./mongodb
    ports:
      - 27017:27017
    command: mongod --smallfiles

  drill:
    build: ./drill
    stdin_open: true
    tty: true
    links:
      - mongo
    ports:
      - 8047:8047

  lab:
    stdin_open: true
    tty: true
    build: .
    working_dir: /app
    volumes:
      - .:/app
    links:
      - mongo
      - drill
    environment:
      - PYTHONPATH=/app
      - PYDRILL_HOST=drill
